# Generated by Django 3.1.7 on 2021-03-22 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pokerstars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=1000)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('rake', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlayDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_players', models.IntegerField()),
                ('total_prizepool', models.IntegerField()),
                ('total_tip', models.IntegerField()),
                ('deduction', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('start_tournament', models.DateTimeField()),
                ('end_tournament', models.DateTimeField()),
                ('buy_in', models.IntegerField()),
                ('rake', models.FloatField()),
                ('total_players', models.IntegerField()),
                ('total_prizepool', models.IntegerField()),
                ('total_rake', models.IntegerField()),
                ('total_tip', models.IntegerField()),
                ('playdate_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pokerstars.playdate')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('external_id', models.BigIntegerField()),
                ('end_date', models.DateTimeField()),
                ('total_players', models.IntegerField()),
                ('state', models.CharField(choices=[(pokerstars.models.StateType['IMPORTED'], 'Imported'), (pokerstars.models.StateType['DONE'], 'Done'), (pokerstars.models.StateType['CANCEL'], 'Cancel')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('BuyIn', 'BuyIn'), ('Payout', 'Payout'), ('Deduction', 'Deduction'), ('Manual', 'Manual')], max_length=255)),
                ('transaction_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('confirm', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account_id', to='pokerstars.account')),
                ('payment_type_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pokerstars.paymenttype')),
                ('to_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account_id', to='pokerstars.account')),
                ('tournament_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokerstars.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('payout', models.FloatField()),
                ('tip', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstars.account')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstars.tournament')),
            ],
        ),
    ]
