# Generated by Django 3.1.7 on 2021-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0002_auto_20210325_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('BuyIn', 'BuyIn'), ('Payout', 'Payout'), ('Tip', 'Tip'), ('Deduction', 'Deduction'), ('Manual', 'Manual')], max_length=255),
        ),
    ]
