# Generated by Django 3.1.7 on 2021-03-25 09:48

from django.db import migrations, models
import pokerstars.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0003_auto_20210325_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.CharField(blank=True, choices=[(pokerstars.models.StateType['IMPORTED'], 'Imported'), (pokerstars.models.StateType['DONE'], 'Done'), (pokerstars.models.StateType['CANCEL'], 'Cancel')], max_length=255, null=True),
        ),
    ]
