# Generated by Django 3.1.7 on 2021-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0004_tournament_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.CharField(blank=True, choices=[('Imported', 'Imported'), ('Done', 'Done'), ('Cancel', 'Cancel')], max_length=255, null=True),
        ),
    ]
