# Generated by Django 3.1.7 on 2021-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0006_remove_tournament_playdate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='buy_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rake',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_prizepool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_rake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_tip',
            field=models.IntegerField(default=0),
        ),
    ]
