# Generated by Django 3.1.7 on 2021-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0007_auto_20210325_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='payout',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rank',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rank',
            name='tip',
            field=models.FloatField(default=0),
        ),
    ]
