# Generated by Django 3.1.7 on 2021-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0008_auto_20210325_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
