# Generated by Django 3.1.7 on 2021-03-27 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstars', '0009_auto_20210325_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_detail',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
